### ISSUE TITLE
TypeError: one character bytes, bytearray or integer expected

### ISSUE THREAD

**Issue by AustinDizzy** [maurosoria/dirs3arch#18]
I'm trying to run dirs3arch on Windows 8.1 (64-bit) with Python 3.4.3 and I'm getting the following error when trying to run a scan with valid arguments:

![image](https://cloud.githubusercontent.com/assets/2718133/10049089/01e5df52-61e4-11e5-877d-16765c178bd7.png)

Is 3.4.3 not supported? By "3.X support", I assumed that included 3.4.3 but [dirs3arch.py:19](https://github.com/maurosoria/dirs3arch/blob/94068b8f9cf3f93ab71f3d1229469fa28c801aeb/dirs3arch.py#L19) tells me otherwise.

![image](https://cloud.githubusercontent.com/assets/2718133/10049401/55161e98-61e5-11e5-87ce-c5a0e0078e5d.png)

**Comment by maurosoria** [comment]
Hi Austin

The bug is in colorama , a thirdparty library that is used to colorize the command prompt.

The bug was fixed, so download the last version (https://pypi.python.org/pypi/colorama), grab the colorama/colorama folder and place it in the thirdparty dir in dirsearch (replace everything)

I'll releasing a new version with this and other fixes soon
